### ISSUE TITLE
找不到指定路径

### ISSUE THREAD

**Issue by larunxn** [zeusees/SSD_License_Plate_Detection#51]
Traceback (most recent call last):
  File "D:/Project/Pycharm/License-Plate-Detector-master/detect_plate.py", line 162, in <module>
    f = show_files("/home/zeusee/plate/", [])
  File "D:/Project/Pycharm/License-Plate-Detector-master/detect_plate.py", line 145, in show_files
    file_list = os.listdir(path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/home/zeusee/plate/'

**Comment by Zane0227** [comment]
这个路径是作者电脑里的路径，替换成自己本地路径即可

**Comment by wxh-zk** [comment]
这个目录下存放的是什么 ，小白求指导呜呜呜。@Zane0227

**Comment by Jinkham** [comment]
> 

你要测试的车牌图片

**Comment by dengdengan** [comment]
> 

想请问一下为什么代码执行完之后只检测了一张图片，或者说检测之后的存储路径在哪里呢
